create sequence hibernate_sequence start 1 increment 1;

create table authority (
    authority_id int8 generated by default as identity,
    name varchar(255) not null,
    primary key (authority_id)
);

create table user_entity (
    id int8  generated by default as identity,
    username varchar(255) not null,
    password varchar(255) not null,
    primary key (id)
);

create table user_authority (
    user_id int8 not null,
    authority_id int8 not null
);

alter table if exists authority
    add constraint authority_name_unique
    unique (name);

alter table if exists user_entity
    add constraint user_entity_username_unique
    unique (username);

alter table if exists user_authority
    add constraint user_authotity_user_id_fk
    foreign key (user_id) references user_entity;

alter table if exists user_authority
    add constraint user_authotity_authotity_id_fk
    foreign key (authority_id) references authority;